---
{{- range $env, $url := .Values.letsencrypt.env }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ $env }}
  namespace: {{ $.Release.Namespace }}
spec:
  acme:
    server: {{ $url }}
    email: {{ $.Values.acme.email | quote }}

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-{{ $env }}

    # ACME DNS-01 provider configurations
    dns01:

      # Here we define a list of DNS-01 providers that can solve DNS challenges
      providers:

        - name: route53
          route53:
            region: {{ $.Values.route53.region | quote }}
---
{{- end }}
