apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: root-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: root-ca
    app.kubernetes.io/instance: {{ template "cert-manager.name" . }}-{{ .Values.env }}
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}
    app.kubernetes.io/part-of: {{ template "cert-manager.name" . }}-{{ .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  secretName: root-ca
  commonName: "Root CA"
  isCA: true
  duration: 87600h
  renewBefore: 72h
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: intermediate-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: intermediate-ca
    app.kubernetes.io/instance: {{ template "cert-manager.name" . }}-{{ .Values.env }}
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}
    app.kubernetes.io/part-of: {{ template "cert-manager.name" . }}-{{ .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  secretName: intermediate-ca
  commonName: "Intermediate CA"
  isCA: true
  duration: 87600h
  renewBefore: 72h
  issuerRef:
    name: root-ca
    kind: Issuer
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: root-ca
  labels:
    app.kubernetes.io/component: root-ca
    app.kubernetes.io/instance: {{ template "cert-manager.name" . }}-{{ .Values.env }}
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}
    app.kubernetes.io/part-of: {{ template "cert-manager.name" . }}-{{ .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  ca:
    secretName: root-ca
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: intermediate-ca
  labels:
    app.kubernetes.io/component: intermediate-ca
    app.kubernetes.io/instance: {{ template "cert-manager.name" . }}-{{ .Values.env }}
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}
    app.kubernetes.io/part-of: {{ template "cert-manager.name" . }}-{{ .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  ca:
    secretName: intermediate-ca
