apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cert-manager.name" . }}-clusterrolebinding
  labels:
    app.kubernetes.io/component: {{ template "cert-manager.name" . }}
    app.kubernetes.io/instance: {{ template "cert-manager.name" . }}-{{ .Values.env }}
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}
    app.kubernetes.io/part-of: {{ template "cert-manager.name" . }}-{{ .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
subjects:
- kind: ServiceAccount
  name: {{ template "cert-manager.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
