apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: selfsigning-issuer
  labels:
    app.kubernetes.io/component: selfsigning-issuer
    app.kubernetes.io/instance: {{ template "cert-manager.name" . }}-{{ .Values.env }}
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: {{ template "cert-manager.name" . }}
    app.kubernetes.io/part-of: {{ template "cert-manager.name" . }}-{{ .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selfSigned: {}
