# Default values for external-dns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

external-dns:
  provider: aws
  aws:
    region: "us-east-1"

  rbac:
    create: true
    serviceAccountName: "external-dns"

  resources:
    limits:
      cpu: 50m
      memory: 50Mi

  metrics:
    enabled: true

  txtOwnerId: "external-dns-prod"
