---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "static-nginx.fullname" . }}
  labels:
{{ include "static-nginx.labels" . | indent 4 }}
  {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "static-nginx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "static-nginx.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.deployment.podLabels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.deployment.podAnnotations }}
      annotations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      strategy:
        type: "RollingUpdate"
        rollingUpdate:
          maxSurge: {{ .Values.deployment.maxSurge | default 1 }}
          maxUnavailable: {{ .Values.deployment.maxUnavailable | default 0 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
