{{- if .Values.mapping }}
---
apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name:  {{ include "static-nginx.fullname" . }}
spec:
  {{- if .Values.mapping.host }}
  host: {{ .Values.mapping.host | quote }}
  {{- end }}
  prefix: {{ .Values.mapping.prefix | default "/" | quote }}
  service: http://{{ include "static-nginx.fullname" . }}.{{ .Release.Namespace }}:80
  {{- if .Values.mapping.headers }}
  headers:
    {{- toYaml .Values.mapping.headers | nindent 4 }}
  {{- end }}
  {{- if .Values.mapping.retry_policy }}
  retry_policy:
    {{- toYaml .Values.mapping.retry_policy | nindent 4 }}
  {{- end }}
{{- end }}
