---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "static-nginx.fullname" . }}
  labels:
{{ include "static-nginx.labels" . | indent 4 }}
spec:
  minAvailable: {{ .Values.deployment.minAvailable | default 1 }}
  selector:
    app.kubernetes.io/name: {{ include "static-nginx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
