apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ambassador-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.tls.secret }}
  issuerRef:
    name: {{ .Values.tls.issuer.name }}
    kind: {{ .Values.tls.issuer.kind }}
  commonName: {{ .Values.tls.commonName }}
  dnsNames:
  - {{ .Values.tls.commonName }}
  acme:
    config:
    - dns01:
        provider: {{ .Values.acme.provider }}
      domains:
      - {{ .Values.tls.commonName }}
