apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ambassador-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.tls.secret }}
  issuerRef:
    name: {{ .Values.tls.issuer.name }}
    kind: {{ .Values.tls.issuer.kind }}
  {{- if .Values.tls.dnsNames }}
  dnsNames:
    {{- toYaml .Values.tls.dnsNames | nindent 4 }}
  {{- end }}
  acme:
    config:
    - dns01:
        provider: {{ .Values.acme.provider }}
      {{- if .Values.tls.dnsNames }}
      domains:
        {{- toYaml .Values.tls.dnsNames | nindent 8 }}
      {{- end }}
