# Default values for kiam.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# Values to be passed to the upstream chart
kiam:
  agent:
    host:
      interface: "!eth0"

    extraHostPathMounts:
      - name: ssl-certs
        mountPath: /etc/ssl/certs
        hostPath: /etc/pki/ca-trust/extracted/pem
        readOnly: true

  server:
    probes:
      serverAddress: 127.0.0.1

    extraHostPathMounts:
      - name: ssl-certs
        mountPath: /etc/ssl/certs
        hostPath: /etc/pki/ca-trust/extracted/pem
        readOnly: true

    useHostNetwork: true
