---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "chartmuseum.fullname" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      app: {{ template "chartmuseum.fullname" . }}
      release: {{ .Release.Name | quote }}

