apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: root-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: root-ca
    app.kubernetes.io/instance: {{ template "kiam.name" . }}-{{ .Values.env }}
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: {{ template "kiam.name" . }}
    app.kubernetes.io/part-of: {{ template "kiam.name" . }}-{{ .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  secretName: root-ca
  commonName: "Kiam Root CA"
  isCA: true
  duration: 87600h
  renewBefore: 72h
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: root-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: root-ca
    app.kubernetes.io/instance: {{ template "kiam.name" . }}-{{ .Values.env }}
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: {{ template "kiam.name" . }}
    app.kubernetes.io/part-of: {{ template "kiam.name" . }}-{{ .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  ca:
    secretName: root-ca
