apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "kiam.name" . }}-agent
  namespace: {{ .Release.Namespace }}

spec:
  secretName: {{ template "kiam.name" . }}-agent-tls
  issuerRef:
    name: root-ca
    kind: Issuer
  commonName: "Kiam Agent"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "kiam.name" . }}-server
  namespace: {{ .Release.Namespace }}

spec:
  secretName: {{ template "kiam.name" . }}-server-tls
  issuerRef:
    name: root-ca
    kind: Issuer
  dnsNames:
    - {{ template "kiam.name" . }}-server
  ipAddresses:
    - 127.0.0.1
