# Default values for k8s-spot-rescheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

k8s-spot-rescheduler:
  image:
    tag: "v0.2.0"
