# Default values for k8s-spot-termination-handler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

k8s-spot-termination-handler:
  image:
    tag: "1.13.7-1"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/lifecycle"
            operator: "In"
            values:
            - "spot"

  tolerations:
  - key: "node-role.kubernetes.io/spot-worker"
    operator: "Equal"
    value: "true"
    effect: "PreferNoSchedule"
