# Default values for chartmuseum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mapping: {}

podDisruptionBudget: {}

# Default values for upstream chart.
chartmuseum:

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 80m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
