# Default values for reloader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

reloader:

  deployment:
    image:
      tag: "v0.0.25"
